version: "3"

services:
  auth-api:
    image: app
    container_name: "app"
    build: ./
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "auth-mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./.data/db:/data/db
    ports:
        - "27017:27017"